name: Deploy Node.js Backend

on:
  push:
    branches:
      - backend
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Change based on your version

      - name: Run setup commands on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no "$EC2_USER@$EC2_HOST" << 'EOF'
          cd backend
          npm install  # Install dependencies on the server
          npm run build  # Build the project on the server
          pm2 restart ecosystem.config.js  # Restart using PM2
          EOF

